### ISSUE TITLE
printf.h: No such file or directory

### ISSUE THREAD

**Issue by jax200** [budryerson/TFMini-Plus#29]
Hello

I am relatively new to this.   I have connected up a TFMini Plus to an Arduino UNO, added this library to /Arduino/libraries, then attempted to run TMFM_example.ino.   On verify I got the following, so not sure what to do.   Thanks!

`TFMP_example:25:10: fatal error: printf.h: No such file or directory
 #include "printf.h"   // Modified to support Intel based Arduino
          ^~~~~~~~~~
compilation terminated.
exit status 1
printf.h: No such file or directory
`

**Comment by budryerson** [comment]
Make sure that the file `printf.h` is in the same folder with your sketch.
`printf.h` is included with the example sketch.

**Comment by Surfer2010** [comment]
In file included from C:\Users\Dom\Documents\Arduino\TFMini-Plus_Budryerson\example\TFMP_example\TFMP_example.ino:25:0:
sketch\printf.h: In function 'void printf_begin()':
sketch\printf.h:30:29: error: 'fdevopen' was not declared in this scope
   fdevopen( &serial_putc, 0 );
                             ^
exit status 1
Fehler beim Kompilieren für das Board DOIT ESP32 DEVKIT V1.

**Comment by ripan-uppsala** [comment]
I am succesfully using your code, thanks :), but instead of printf.h used the official download "PrintEx.h" in this case on a Nano Every.

#include "PrintEx.h"                           // To support printf
StreamEx mySerial = Serial;               // Creat a StreamEx object

and renamed all printf instances to mySerial.printf
