### ISSUE TITLE
Recommendation?

### ISSUE THREAD

**Issue by espresso0000** [budryerson/TFMini-Plus#3]
Wanting to inquire how your code differs from senegalo library for the TFMini-Plus, and recommendation for one over the other?  Just got my first of several units and excited to be able to find working code and get them tested.  Thanks

https://github.com/senegalo/TFMiniPlus

**Comment by budryerson** [comment]
It's pretty exciting do find out there's another library.  I'm anxious to take it apart and learn from it.  If I'd known about this, maybe I wouldn't have had to write one myself.At first glance, every command in his library has its own method.  Mine has two: getData & sendCommand. getData passes back all three values, sendCommand builds a command string from your choice of command and parameters.Anyway,  right now I'm having some Scotch and a cigar, so I'll look at this later and get back to you. Thanks for writing. Bud RyersonSent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: espresso0000 <notifications@github.com> Date: 5/17/19  1:26 PM  (GMT-08:00) To: budryerson/TFMini-Plus <TFMini-Plus@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [budryerson/TFMini-Plus] Recommendation? (#3) Wanting to inquire how your code differs from senegalo library for the TFMini-Plus, and recommendation for one over the other?  Just got my first of several units and excited to be able to find working code and get them tested.  Thanks
https://github.com/senegalo/TFMiniPlus

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/budryerson/TFMini-Plus/issues/3?email_source=notifications\u0026email_token=ABWD6AXE6LBW67WRBBY3V5DPV4IJDA5CNFSM4HNYF2XKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GUPMXEQ",
"url": "https://github.com/budryerson/TFMini-Plus/issues/3?email_source=notifications\u0026email_token=ABWD6AXE6LBW67WRBBY3V5DPV4IJDA5CNFSM4HNYF2XKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GUPMXEQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
